apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: python-ugqhozio
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-ugqhozio 
  name: python-ugqhozio
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: python-ugqhozio 
