apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: python-ugqhozio-gitops
  description: This is GitOps manifest for python-ugqhozio   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=python-ugqhozio
    backstage.io/kubernetes-id: python-ugqhozio 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: chetna14manku-org/python-ugqhozio-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:python-ugqhozio
